#!/usr/bin/env python3

"""This demo script simultaneously displays the koi fish video will writing haptic output
to the haptic display via USB. Both the video and haptic output will loop continuously
until the user presses the 'B' keyboard key.

To run, it requires both the input video and the output.txt file generated by the
visual-haptic algorithm preprocessing code."""

###### USER SETTINGS ######
FILENAME = "algo_input_data/datakoi_output.txt"
VIDEONAME = "algo_input_videos/video_koi.mp4"
SERIAL_ACTIVE = True # if False, just runs the algorithm without sending to HV switches
COM_A = "COM14" # port for MINI switches 1-10
COM_B = "COM9" # port for MINI switches 11-20
COM_C = "COM16" # port for MINI swiches 21-28

###### INITIALIZATIONS ######
import cv2
import time
import haptic_utils.haptic_map as haptic_map # my custom file
import haptic_utils.USB as USB # my custom file
import haptic_utils.algo_preprocessing as algo
from numpy import genfromtxt

###### MAIN ######
# Load data
data=genfromtxt(FILENAME,delimiter=',')[:,0:28]
data_length = data.shape[0]
data_intensity = data.reshape((data_length,4,7))
data_sequence = []
data_smooth = algo.smooth(data_intensity, size=5)

for array in data_smooth: data_sequence.append(array)
data_sequence.reverse()

frame_rate = 15

# Set up USBWriter and intensity map:
serial_ports = [COM_A, COM_B, COM_C]
serial_writer = USB.SerialWriter(serial_ports, serial_active=SERIAL_ACTIVE)

# Preprocess data:
output_data = haptic_map.make_output_data(data_sequence,
                                        freq_range=(20,20),
                                        duty_range=(0,0.5))

# Preprocess video:
video_data = []
cap = cv2.VideoCapture(VIDEONAME)
while True:
    ret,img = cap.read()
    if ret:
        video_data.append(img)
    else:
        break
video_data.reverse()

# Enable HV!!!
serial_writer.HV_enable()

t_sum = 0
while True:
    isClose=False # break condition
    video_sequence = video_data.copy()
    packet_sequence = output_data.packet_sequence.copy() # copy packet sequence
    intensity_sequence = output_data.intensity_sequence.copy()
    while True:
        if len(packet_sequence)>0 and len(video_sequence)>0: # if frame exists, run; otherwise, video is finished->loop back to beginning
            t_start = time.time()
            # send to USB:
            serial_writer.write_packets_to_USB(packet_sequence.pop())
            # Display video:
            video_sequence.pop()
            # intensity_sequence.pop()
            cv2.namedWindow('Video',cv2.WINDOW_KEEPRATIO)
            cv2.imshow('Video',video_sequence.pop())
            # cv2.namedWindow('Intensity',cv2.WINDOW_KEEPRATIO)
            # cv2.imshow('Intensity',intensity_sequence.pop())

            if(cv2.waitKey(10) & 0xFF == ord('b')): # BREAK OUT OF LOOP WHEN "b" KEY IS PRESSED!
                isClose = True # assign stop flag
                break

            # maintain constant loop frame rate:
            time.sleep(max(1/frame_rate-(time.time()-t_start), 0)) 
        else: 
            break # video is finished, break and reset frame count

    if isClose: 
        break # user pressed 'b', stop script
    
print(t_sum)
# Disable HV!!!
serial_writer.HV_disable()
time.sleep(0.5)
